holding alt to give custom modifiers to ball throw
dylanpiera/Foundry-Pokemon-Tabletop-United-System pull request #383
Opened 2023-05-07 08:11 UTC by Ellamental2

on the sidebar if you hold alt whilst clicking a pokeball from the pokeball menu you will be given the following prompt.

![image](https://user-images.githubusercontent.com/43385250/236665637-f5e413bb-5404-4c49-855d-5867698f5e68.png)
(fields default to 0)

this allows user to enter custom accuracy and capture rate modifiers.
If the GM has the gm prompts enabled the GM will be informed of these modifiers.

![image](https://user-images.githubusercontent.com/43385250/236665679-9376c592-e1d7-472a-85de-127d8c29a0f1.png)

and these modifiers effect the accuracy and capture rate of pokeball throws

Before modifiers:
![image](https://user-images.githubusercontent.com/43385250/236665714-b8ba4a3b-85d6-4cba-b4ac-898e6bf86f8e.png)

After Modifiers:
![image](https://user-images.githubusercontent.com/43385250/236665769-87988047-fd5f-428b-a617-044bc93e0fe6.png)

2023-05-07 08:18 UTC, Ellamental2 commented
altered the capture rate mod to match the pokeball capture rates, user can now enter a negative number and it will be added to the roll, rather than the DC. eg:
0 modifiers:
![image](https://user-images.githubusercontent.com/43385250/236666026-38ce3c3a-cba8-4f87-93f5-efe6ca8b8140.png)


-20 Modifier:
![image](https://user-images.githubusercontent.com/43385250/236666069-8f521d36-efb0-414d-bcf1-732b265fdcdd.png)
![image](https://user-images.githubusercontent.com/43385250/236666087-5535b4f4-16da-41e3-b756-0d46ed3fd7b6.png)

2023-05-22 10:47 UTC, dylanpiera requested changes

2023-05-22 10:47 UTC, dylanpiera commented on module/sidebar/components/menu-component.js
> +                    });
In this section of code you're doing a lot of editing out-of-scope, while in this case it works, it's not proper to edit the `args` like this, nor calling the await as such.

Instead I'd change the callbacks to be something like:
```js
callback: (html) => {
    const args = {
        accuracyModifier: parseInt(html.find('[name="accuracyModifier"]').val()),
        captureRateModifier: parseInt(html.find('[name="captureRateModifier"]').val())
    }
    resolve(args)
}
```
which can even be simplified to `resolve({/*params*/})`

Then for the rejects you can do the logging inside the callback
```js
callback: () => {
    console.log("User cancelled the dialog");
    reject();
}
```
Meanwhile returning `undefined`.

Then at the top we can simply call
`const args = await new Promise(/*etc.*/);`

As in this file there are no references to args.property we don't have to do a null check here and instead can perform that in the `throwPokeball` or `throwPokeballRequest` methods, where either null checks or null coalescing can be used.

2023-05-22 10:47 UTC, dylanpiera commented on module/combat/effects/pokeball_effects.js
> +    accuracyBonus += thrower?.data?.data?.modifiers?.acBonus?.total ?? 0;
```suggestion
    const accuracyBonus = args?.accuracyModifier ?? 0 + thrower?.data?.data?.modifiers?.acBonus?.total ?? 0;
```

2023-09-15 08:20 UTC, closed without merging